server:
  connection-timeout: 1000    # socket 커넥션 타임아웃
  tomcat:
    max-connections: 2 # 3 way 핸드웨이크는 맺어졌지만, 동시에 처리 할 수 있는 커넥션 수. for connection_timeout_test
    # 커넥터는 NIO 커넥터로 하나의 스레드에서 돌고 있음.
    max-threads: 100  # 최대 Worker 스레드 수
    min-spare-threads: 5 # 최소 대기 worker 스레드 수
